name: Tracee Pipeline Scan
on: [pull_request]

jobs:
  Tracee-Scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start Tracee profiling in background
      uses: simar7/tracee-action@v0.1.0-start

    - name: Your CI Pipeline Step
      run: for i in {1..20}; do sleep 2 && strace ls; done

    - name: Stop and Check Tracee results and create a PR
      uses: simar7/tracee-action@5a7b8a57a6de4e9286e8ec5504f6b53bffbbd1af