name: Tracee Pipeline Scan
on: [pull_request]

jobs:
  Tracee-Scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start Tracee profiling in background
      uses: simar7/tracee-action@v0.2.0-start

    - name: Your CI Pipeline Step
      run: for i in {1..20}; do sleep 2; done

    - name: Stop and Check Tracee results and create a PR
      uses: simar7/tracee-action@9d3ae04b4d6927901896ac7b398c58ae5e2f62f1
      with:
        fail-on-diff: "true"
        create-pr: "true"
